from typing import  Optional,List
from typing_extensions import TypedDict, NotRequired, Annotated
from .objects import Reporter
import operator

class ReporterState(TypedDict):
    topic: str  #Research Topic
    max_reporters: int # Number of reporters
    human_feedback_on_reporters: NotRequired[Optional[str]] #Human feedback for what is generated
    reporters: NotRequired[List[Reporter]] #List of all our reporters

class ReporterInterviewState(TypedDict):
    reporter_generated_questions_and_answers: Annotated[list,operator.add] # This is a list of questions generated by the reporter
    reporter: Reporter
    tavily_web_search_response: Annotated[list, operator.add] #source of docs
    finished_interview_between_reporter_and_expert: str
    sections: list
    max_num_turns: int
    
class ResearchGraphState(TypedDict):
    topic: str # Research topic
    max_reporters: int # Number of reporters
    human_feedback_on_reporters: NotRequired[Optional[str]] # Human feedback
    reporters: List[Reporter] # Reporter asking questions
    sections: Annotated[list, operator.add] # Send() API key
    introduction: str # Introduction for the final report
    content: str # Content for the final report
    conclusion: str # Conclusion for the final report
    final_report: str # Final report